server:
  port: 8282

#spring:
#  datasource:
#    url: jdbc:h2:mem:inventory
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true