insert into warehouses (name, location, size, capacity) values ('Tern, royal', 'Kyzyl-Kyya', 49, 186);
insert into warehouses (name, location, size, capacity) values ('Boar, wild', 'Golem', 41, 132);
insert into warehouses (name, location, size, capacity) values ('Red-necked wallaby', 'Kotel', 33, 261);
insert into warehouses (name, location, size, capacity) values ('Horned rattlesnake', 'Tsagaan-Owoo', 86, 413);
insert into warehouses (name, location, size, capacity) values ('Potoroo', 'Ujsoły', 68, 207);
insert into items (name, description, size) values ('Lemmon''s Needlegrass', 'Poaceae', 9);
insert into items (name, description, size) values ('Bamberger''s Hypnum Moss', 'Hypnaceae', 9);
insert into items (name, description, size) values ('Ross'' Sedge', 'Cyperaceae', 10);
insert into items (name, description, size) values ('Chinese White Poplar', 'Salicaceae', 10);
insert into items (name, description, size) values ('Isely''s Senna', 'Fabaceae', 1);
insert into items (name, description, size) values ('Spike Lichen', 'Caliciaceae', 6);
insert into items (name, description, size) values ('Spotted Mock Orange', 'Hydrangeaceae', 6);
insert into items (name, description, size) values ('Placidiopsis Lichen', 'Verrucariaceae', 3);
insert into items (name, description, size) values ('Eastern Mojave Buckwheat', 'Polygonaceae', 4);
insert into items (name, description, size) values ('Southern Mountain Misery', 'Rosaceae', 4);
insert into items (name, description, size) values ('Dunchi Fiber', 'Fabaceae', 8);
insert into items (name, description, size) values ('Bitter Fleabane', 'Asteraceae', 7);
insert into items (name, description, size) values ('Sonoran Prairie Clover', 'Fabaceae', 2);
insert into items (name, description, size) values ('Rincon Ridge Ceanothus', 'Rhamnaceae', 4);
insert into items (name, description, size) values ('Wild Comfrey', 'Boraginaceae', 8);
insert into items (name, description, size) values ('Nuttall''s Sunflower', 'Asteraceae', 1);
insert into items (name, description, size) values ('Cinnamon Fern', 'Osmundaceae', 8);
insert into items (name, description, size) values ('Rose Moss', 'Portulacaceae', 8);
insert into items (name, description, size) values ('Cooper''s Wild Cabbage', 'Brassicaceae', 9);
insert into items (name, description, size) values ('Hawai''i Korthal Mistletoe', 'Viscaceae', 9);